### ISSUE TITLE
Operator as built from master and available on quay.io - fails to start

### ISSUE THREAD

**Issue by ldimaggi** [redhat-developer/openshift-jenkins-operator#37]
Steps to recreate:
* Install Operator from Operator source:
```
---
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: openshift-jenkins-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: redhat-developer
```
* Create Operator subscription and instance - observe this event:
```
PodPjenkins-operator-579f778765-2gbsf
NamespaceNSopenshift-operators
a few seconds ago
Generated from kubelet on ip-10-0-157-243.us-east-2.compute.internal
3 times in the last few seconds
Error: container create failed: container_linux.go:345: starting container process caused "exec: \"jenkins-operator\": executable file not found in $PATH"
```
