### ISSUE TITLE
Build resulting from creating pipeline project does not progress from "New" state

### ISSUE THREAD

**Issue by ldimaggi** [redhat-developer/openshift-jenkins-operator#49]
Steps to recreate:
* From the master branch
* run local
* oc apply -f (either the ephemeral or persistent CR for Jenkins operator)
* oc new-app https://github.com/waveywaves/nodejs-ex --context-dir openshift/pipelines

An oc build resource is created, but the build operation is not performed - the build never appears in the Jenkins console

```
oc get build.build.openshift.io/nodejs-ex-1 -o yaml
.
.
status:
  config:
    kind: BuildConfig
    name: nodejs-ex
    namespace: jenkins-test
  output: {}
  phase: New
```

```
oc logs -f bc/nodejs-ex
error: the pipeline strategy build nodejs-ex-1 does not yet contain the log URL; wait a few moments, then try again
```
